<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Notifications\Notifiable;
use Laravel\Sanctum\HasApiTokens;
class DMMaster extends Model
{
    use HasApiTokens, HasFactory, Notifiable;

    protected $table="dmmaster";
    protected $primaryKey = 'VSNNo';

    public $timestamps = false;

protected $fillable = [
    'VSNNo'
      ,'EventNo'
      ,'QuoteNo'
      ,'ChargeNo'
      ,'VesselRefNo'
      ,'Department'
      ,'CustomerRefNo'
      ,'Terms'
      ,'BranchCode'
      ,'ExtAmount'
      ,'EstLines'
      ,'CustomerName'
      ,'VesselName'
      ,'Location'
      ,'Buyer'
      ,'POMadeNO'
      ,'POMadeDate'
      ,'CustomerCode'
      ,'BContactPerson'
      ,'BillingAddress'
      ,'BTelephoneNo'
      ,'BFaxNo'
      ,'BEmailAddress'
      ,'BWeb'
      ,'Status'
      ,'Country'
      ,'CusCode'
      ,'InternalComments'
      ,'City'
      ,'DispatchDate'
      ,'DispatchTime'
      ,'DeliveryDes'
      ,'InvDiscPer'
      ,'InvDiscAmt'
      ,'NetAmount'
      ,'InvDate'
      ,'InvTime'
      ,'OrderQty'
      ,'RecQty'
      ,'DeliveredQty'
      ,'RtnQty'
      ,'MissingQty'
      ,'SoldQty'
      ,'PurchaseOrderNo'
      ,'OrderDate'
      ,'PullQty'
      ,'PullDate'
      ,'PullTime'
      ,'PullDes'
      ,'DeliveryOrderNo'
      ,'TotGPAmt'
      ,'VendorActCode'
      ,'ChkDirectDelivery'
      ,'Des'
      ,'CustomerActCode'
      ,'CostAmt'
      ,'GPPer'
      ,'VSNInvoiceNo'
      ,'CreateInvoice'
      ,'GPCostAmt'
      ,'Atten'
      ,'ReceivedAmt'
      ,'PaidAmt'
      ,'BankInfo'
      ,'VATPer'
      ,'VATAmt'
      ,'DeliveryCharges'
      ,'WorkUserActive'
      ,'DepartmentCode'
      ,'DepartmentName'
      ,'Oe'
      ,'ReturnVia'
      ,'EstLineQuote'
      ,'CstItems'
      ,'PricingItems'
      ,'BidDueDate'
      ,'DueTime'
      ,'DiscPer'
      ,'GSTPer'
      ,'QDate'
      ,'QTime'
      ,'ChkQuoteEntry'
      ,'ChkCosting'
      ,'ChkPricing'
      ,'QsentDate'
      ,'QSenttime'
      ,'Header'
      ,'ValueAmount'
      ,'CostAmount'
      ,'GPAmount'
      ,'StatusColorCode'
      ,'StatusCode'
      ,'CustCode'
      ,'Freight'
      ,'WorkUser'
      ,'USDRate'
      ,'comments'
      ,'GivenDisc'
      ,'AgentCode'
      ,'AgentName'
      ,'AgentPer'
      ,'PortCode'
      ,'PortName'
      ,'Priority'
      ,'SaleReturnQty'
      ,'SaleReturnAmount'
      ,'ShippedDate'
      ,'ShippedTime'
      ,'GodownCode'
      ,'GodownName'
      ,'DMReturnQty'
      ,'DMReturnAmt'
      ,'DMMoveToStock'
      ,'DMMoveToStockAmt'
      ,'DMMissingQty'
      ,'DMMissingAmt'
      ,'RTNDate'
      ,'RTNTime'
      ,'ReturnAmt'
      ,'DMMissingExpQty'
      ,'DMMissingExpAmt'

];
}
