<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Laravel\Sanctum\HasApiTokens;
use Illuminate\Notifications\Notifiable;
class OrderModel extends Model
{

    use HasApiTokens, HasFactory, Notifiable;

    protected $table="orderdetail";
    protected $primaryKey = 'ID';

    public $timestamps = false;

protected $fillable = [
       "ID"
      ,"PONO"
      ,"OrderDate"
      ,"VSNNo"
      ,"EventNo"
      ,"QuoteNo"
      ,"ItemCode"
      ,"ItemName"
      ,"Qty"
      ,"PUOM"
      ,"Price"
      ,"EstPrice"
      ,"BranchCode"
      ,"DepartmentName"
      ,"QID"
      ,"STKBuyOut"
      ,"ProductName"
      ,"Freight"
      ,"GPAmount"
      ,"VendorName"
      ,"VendorPrice"
      ,"OurPrice"
      ,"OriginName"
      ,"VPart"
      ,"CustomerNotes"
      ,"VendorNotes"
      ,"InternalBuyerNotes"
      ,"VendorCode"
      ,"VCategoryName"
      ,"GPRate"
      ,"LastDate"
      ,"Alternative"
      ,"OurUOM"
      ,"DiscIncomePer"
      ,"DiscIncomeAmt"
      ,"IMPA"
      ,"POMadeNo"
      ,"POMadeDate"
      ,"ChkBuy"
      ,"WorkUser"
      ,"OrderQty"
      ,"RecQty"
      ,"NotRecQty"
      ,"OverQty"
      ,"DeliveredQty"
      ,"ReturnQty"
      ,"MissingQty"
      ,"SoldQty"
      ,"DeliveredAmount"
      ,"InvoiceAmount"
      ,"PurRetQty"
      ,"PullQty"
      ,"PullDate"
      ,"PullTime"
      ,"PullStockQty"
      ,"PullAmount"
      ,"PullShortQty"
      ,"Atten"
      ,"SNo"
      ,"CostPrice"
      ,"GPCostAmt"
      ,"GodownCode"
      ,"QDate"
      ,"CustomerName"
      ,"VesselName"
      ,"SuggestPrice"
      ,"Total"
      ,"Updated"
      ,"TotalCost"
      ,"IMPAItemCode"
      ,"PortCode"
      ,"PortName"
      ,"OrderAmount"
      ,"AgentCode"
      ,"AgentName"
      ,"AgentPer"
      ,"UpdatedDate"
      ,"FreightRate"
      ,"HasmateNo"
      ,"HasmateWeight"
      ,"HasMate"
      ,"SaleReturnQty"
      ,"SaleReturnAmount"
      ,"OverCommitQty"
      ,"GodownName"
      ,"DiscPerVendor"
      ,"ReturnCostAmt"
      ,"VendorActCode"
      ,"CancelQty"
      ,"MoveToStockQty"
      ,"Cost"
      ,"CancelQtyPO"
      ,"OrderQtyPO"
      ,"StockQty"
      ,"CurrChkBuy"
      ,"VendorPartNo"
      ,"StockLocation"
];
}
