<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Laravel\Sanctum\HasApiTokens;
use Illuminate\Notifications\Notifiable;
class OrderMasterModel extends Model
{
    use HasApiTokens, HasFactory, Notifiable;

    protected $table="ordermaster";

    protected $primaryKey="ID";

    public $timestamps = false;

protected $fillable = [
    'ID'
    ,'VSNNo'
    ,'EventNo'
    ,'QuoteNo'
    ,'PONo'
    ,'VesselRefNo'
    ,'Department'
    ,'CustomerRefNo'
    ,'Terms'
    ,'BranchCode'
    ,'ExtAmount'
    ,'EstLines'
    ,'CustomerName'
    ,'VesselName'
    ,'Location'
    ,'Buyer'
    ,'POMadeNO'
    ,'POMadeDate'
    ,'CustomerCode'
    ,'BContactPerson'
    ,'BillingAddress'
    ,'BTelephoneNo'
    ,'BFaxNo'
    ,'BEmailAddress'
    ,'BWeb'
    ,'Status'
    ,'Country'
    ,'CusCode'
    ,'InternalComments'
    ,'City'
    ,'DispatchDate'
    ,'DispatchTime'
    ,'DeliveryDes'
    ,'InvDiscPer'
    ,'InvDiscAmt'
    ,'NetAmount'
    ,'InvDate'
    ,'InvTime'
    ,'OrderQty'
    ,'RecQty'
    ,'DeliveredQty'
    ,'RtnQty'
    ,'MissingQty'
    ,'SoldQty'
    ,'PurchaseOrderNo'
    ,'OrderDate'
    ,'PullQty'
    ,'PullDate'
    ,'PullTime'
    ,'PullDes'
    ,'DeliveryOrderNo'
    ,'TotGPAmt'
    ,'VendorActCode'
    ,'ChkDirectDelivery'
    ,'Des'
    ,'CustomerActCode'
    ,'CostAmt'
    ,'GPPer'
    ,'VSNInvoiceNo'
    ,'CreateInvoice'
    ,'GPCostAmt'
    ,'Atten'
    ,'ReceivedAmt'
    ,'PaidAmt'
    ,'BankInfo'
    ,'VATPer'
    ,'VATAmt'
    ,'DeliveryCharges'
    ,'WorkUserActive'
    ,'DepartmentCode'
    ,'DepartmentName'
    ,'Oe'
    ,'ReturnVia'
    ,'EstLineQuote'
    ,'CstItems'
    ,'PricingItems'
    ,'BidDueDate'
    ,'DueTime'
    ,'DiscPer'
    ,'GSTPer'
    ,'QDate'
    ,'QTime'
    ,'ChkQuoteEntry'
    ,'ChkCosting'
    ,'ChkPricing'
    ,'QsentDate'
    ,'QSenttime'
    ,'Header'
    ,'ValueAmount'
    ,'CostAmount'
    ,'GPAmount'
    ,'StatusColorCode'
    ,'StatusCode'
    ,'CustCode'
    ,'Freight'
    ,'WorkUser'
    ,'USDRate'
    ,'comments'
    ,'GivenDisc'
    ,'AgentCode'
    ,'AgentName'
    ,'AgentPer'
    ,'PortCode'
    ,'PortName'
    ,'Priority'
    ,'SaleReturnQty'
    ,'SaleReturnAmount'
    ,'ChkSendEmail'
    ,'DueDate'
    ,'CrNoteAmt'
    ,'SaleReturnDate'
    ,'SaleReturnTime'
    ,'ChqNo'
    ,'ShippedDate'
    ,'ShippedTime'
    ,'LadingNo'
    ,'ChkShipped'
    ,'RVNo'
    ,'GodownCode'
    ,'GodownName'
    ,'VendorDiscPer'
    ,'RvDate'
    ,'CrNotePer'
    ,'AVIRebatePer'
    ,'AgentCommPer'
    ,'SlsCommPer'
    ,'CrNoteAmount'
    ,'AVIRebateAmt'
    ,'AgentCommAmt'
    ,'SlsCommAmt'
    ,'VesselCode'
    ,'ChkSevenSeasDelivery'
    ,'PullStockPDFPath'
    ,'PullTicketPrintedDate'
    ,'ChkPullTicketPrinted'
    ,'StockPulledDateTime'
    ,'ChkStockPulled'
    ,'SaleAmtWODisc'
    ,'MissingAmount'
    ,'NotDeliveredDate'
    ,'NotDeliveredWorkUser'
    ,'NotDeliveredNetAmount'
    ,'NotDeliveredQty'
    ,'PDFPATHDO'
    ,'PDFPATHINV'
];
}
